# Generated by Django 2.1.7 on 2019-03-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodJobMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frName', models.CharField(max_length=100)),
                ('toName', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('cardpath', models.CharField(max_length=100)),
            ],
        ),
    ]
