# Generated by Django 2.1.7 on 2019-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_goodjobmsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodjobmsg',
            name='savedCardPath',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
    ]
